services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: "django-db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user-password"
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data:
